import pandas as pd
from streamlit_gsheets import GSheetsConnection
import gspread
from oauth2client.service_account import ServiceAccountCredentials

import streamlit as st

scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_dict(st.secrets["google_sheets_credentials"], scope)
client = gspread.authorize(creds)

spreadsheet = client.open_by_key(st.secrets["google_sheets"]["spreadsheet_id"])

worksheet = spreadsheet.worksheet('IndicatorNames')
data = worksheet.get_all_values()

df = pd.DataFrame(data, columns = ['Indicator Name'])

all_indicators = []

for index, row in df.iterrows():
    all_indicators.append(row['Indicator Name'])

all_indicators = all_indicators[1:] #remove the first row

worksheet = spreadsheet.worksheet('Indic_MetaData')
data = worksheet.get_all_values()

df_indic = pd.DataFrame(data, columns = ['Indicator Name', 'Indicator Description','Indicator Source'])
df_indic = df_indic.reset_index() #indicators_dataset

#poverty indicators
spreadsheet_2 = client.open_by_key(st.secrets["google_sheets"]["spreadsheet_id"])
pop_sheet_2 = spreadsheet_2.worksheet('TotPop')
pop_data_2 = pop_sheet_2.get_all_values()

years_list = [
    '1960',
    '1961',	'1962','1963',	'1964', '1965','1966','1967','1968','1969','1970','1971','1972','1973','1974',
    '1975',	'1976',	'1977','1978','1979','1980','1981','1982','1983','1984','1985', '1986',	'1987',	'1988',	
    '1989',	'1990',	'1991',	'1992',	'1993',	'1994',	'1995',	'1996',	'1997',	'1998',	'1999',	'2000',	'2001',	'2002',	
    '2003',	'2004',	'2005',	'2006',	'2007',	'2008',	'2009',	'2010',	'2011',	'2012',	'2013',	'2014',	'2015',	'2016',	
    '2017',	'2018','2019','2020','2021','2022','2023']

pop_df = pd.DataFrame(pop_data_2, columns = ['Country Name','Country Code','Indicator Name','Indicator Code',	'1960',
    '1961',	'1962','1963',	'1964', '1965','1966','1967','1968','1969','1970','1971','1972','1973','1974',
    '1975',	'1976',	'1977','1978','1979','1980','1981','1982','1983','1984','1985', '1986',	'1987',	'1988',	
    '1989',	'1990',	'1991',	'1992',	'1993',	'1994',	'1995',	'1996',	'1997',	'1998',	'1999',	'2000',	'2001',	'2002',	
    '2003',	'2004',	'2005',	'2006',	'2007',	'2008',	'2009',	'2010',	'2011',	'2012',	'2013',	'2014',	'2015',	'2016',	
    '2017',	'2018','2019','2020','2021','2022','2023'])

#GDP
spreadsheet_gdp = client.open_by_key(st.secrets["google_sheets"]["spreadsheet_id"])
gdp_sheet = spreadsheet_gdp.worksheet('GDP_Data')
gdp_data = gdp_sheet.get_all_values()

#Initialize classification options
poverty_choices = ["Poverty headcount ratio at $6.85 a day (2017 PPP) (% of population)", 
"Multidimensional poverty headcount ratio (UNDP) (% of population)",
"Poverty gap at $2.15 a day (2017 PPP) (%)",
"Proportion of population pushed or further pushed below the 60% median consumption poverty line by out-of-pocket health expenditure (%)",
"Proportion of population pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Poverty headcount ratio at national poverty lines (% of population)",
"Poverty headcount ratio at $3.65 a day (2017 PPP) (% of population)",
"Proportion of population pushed or further pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)", 
"Proportion of population pushed below the 60% median consumption poverty line by out-of-pocket health expenditure (%)", 
"Proportion of population pushed further below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Poverty headcount ratio at societal poverty line (% of population)",
"Poverty gap at $3.65 a day (2017 PPP) (%)",
"Poverty headcount ratio at $2.15 a day (2017 PPP) (% of population)",
"Proportion of population pushed or further pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Proportion of population pushed further below the 60% median consumption poverty line by out-of-pocket health care expenditure (%)",
"Poverty gap at $6.85 a day (2017 PPP) (%)", 
"Multidimensional poverty headcount ratio (World Bank) (% of population)",
"Proportion of population pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Proportion of population pushed further below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)"]

education_choices = [
"Share of youth not in education, employment or training, total (% of youth population)",
"Government expenditure on education, total (% of government expenditure)",
"Current education expenditure, tertiary (% of total expenditure in tertiary public institutions)",
"Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)",
"Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative)", 
"Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)",
"Secondary education, teachers, female", 
"Trained teachers in upper secondary education, male (% of male teachers)", 
"Trained teachers in lower secondary education, male (% of male teachers)",
"Secondary education, pupils (% female)", 
"Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)", 
"Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)",
"Trained teachers in primary education, male (% of male teachers)",
"Primary education, pupils (% female)", 
"Educational attainment, at least completed primary, population 25+ years, male (%) (cumulative)",
"Trained teachers in preprimary education, female (% of female teachers)",
"Account ownership at a financial institution or with a mobile-money-service provider, primary education or less (% of population ages 15+)",
"Government expenditure on education, total (% of GDP)", 
"Expenditure on secondary education (% of government expenditure on education)",
"Current education expenditure, total (% of total expenditure in public institutions)", 
"Tertiary education, academic staff (% female)",
"Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)", 
"Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative)",
"Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)", 
"Secondary education, teachers (% female)", 
"Trained teachers in upper secondary education (% of total teachers)", 
"Trained teachers in lower secondary education (% of total teachers)",
"Secondary education, general pupils Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)", 
"Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative)", 
"Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)",
"Trained teachers in primary education (% of total teachers)",
"Gross intake ratio in first grade of primary education, female (% of relevant age group)",
"Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)",
"Trained teachers in preprimary education, male (% of male teachers)",
"Compulsory education, duration (years)",
"Account ownership at a financial institution or with a mobile-money-service provider, secondary education or more (% of population ages 15+)",
"Share of youth not in education, employment or training, female (% of female youth population)", 
"Unemployment with intermediate education, female (% of female labor force with intermediate education)", 
"Unemployment with advanced education (% of total labor force with advanced education)",
"Labor force with intermediate education, female (% of female working-age population with intermediate education)",
"Labor force with advanced education (% of total working-age population with advanced education)",
"Share of youth not in education, employment or training, male (% of male youth population)",
"Unemployment with intermediate education (% of total labor force with intermediate education)",
"Unemployment with basic education, male (% of male labor force with basic education)",
"Unemployment with advanced education, female (% of female labor force with advanced education)",
"Labor force with intermediate education (% of total working-age population with intermediate education)",
"Labor force with basic education, male (% of male working-age population with basic education)",
"Labor force with advanced education, female (% of female working-age population with advanced education)",
"Current education expenditure, primary (% of total expenditure in primary public institutions)",
"Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)",
"Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)",
"Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative)",
"Trained teachers in secondary education (% of total teachers)", 
"Trained teachers in secondary education, male (% of male teachers)",
"Trained teachers in secondary education, female (% of female teachers)",
"Secondary education, vocational pupils", 
"Secondary education, general pupils (% female)", 
"Secondary education, duration (years)",
"Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)",
"Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative)",
"Primary education, teachers",
"Gross intake ratio in first grade of primary education, male (% of relevant age group)",
"Primary education, duration (years)",
"Trained teachers in preprimary education (% of total teachers)",
"Share of youth not in education, employment or training, total (% of youth population) (modeled ILO estimate)",
"Expenditure on tertiary education (% of government expenditure on education)",
"Expenditure on primary education (% of government expenditure on education)", 
"Current education expenditure, secondary (% of total expenditure in secondary public institutions)",
"Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)", 
"Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)",
"Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)",
"Secondary education, teachers Trained teachers in upper secondary education, female (% of female teachers)",
"Trained teachers in lower secondary education, female (% of female teachers)",
"Secondary education, vocational pupils (% female)",
"Secondary education, pupils", 
"Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)", 
"Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)",
"Primary education, teachers (% female)",
"Trained teachers in primary education, female (% of female teachers)",
"Gross intake ratio in first grade of primary education, total (% of relevant age group)",
"Primary education, pupils", 
"Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative)",
"Preprimary education, duration (years)",
"Adjusted savings: education expenditure (% of GNI)",
"Share of youth not in education, employment or training, female (% of female youth population) (modeled ILO estimate)",
"Unemployment with basic education (% of total labor force with basic education)", 
"Unemployment with advanced education, male (% of male labor force with advanced education)",
"Labor force with basic education (% of total working-age population with basic education)",
"Labor force with advanced education, male (% of male working-age population with advanced education)",
"Share of youth not in education, employment or training, male (% of male youth population)  (modeled ILO estimate)", 
"Unemployment with intermediate education, male (% of male labor force with intermediate education)", 
"Unemployment with basic education, female (% of female labor force with basic education)",
"Labor force with intermediate education, male (% of male working-age population with intermediate education)",
"Labor force with basic education, female (% of female working-age population with basic education)",
"Adjusted savings: education expenditure (current US$)"
]

land_ag_choices = [
"Agricultural land (sq. km)",
"Arable land (% of land area)",
"Cereal yield (kg per hectare)",
"Crop production index (2014-2016 = 100)", 
"Land area (sq. km)", 
"Forest area (sq. km)", 
"Rural land area where elevation is below 5 meters (% of total land area)",
"Agriculture, forestry, and fishing, value added (constant 2015 US$)",
"Food production index (2014-2016 = 100)", 
"Rural land area (sq. km)", 
"Forest area (% of land area)", 
"Urban land area where elevation is below 5 meters (sq. km)", 
"Land under cereal production (hectares)", 
"Agricultural land (% of land area)",
"Food production index (2014-2016 = 100)", 
"Rural land area (sq. km)", 
"Forest area (% of land area)",
"Urban land area where elevation is below 5 meters (sq. km)", 
"Land under cereal production (hectares)", 
"Agricultural land (% of land area)",
"Livestock production index (2014-2016 = 100)", 
"Urban land area (sq. km)", 
"Agricultural irrigated land (% of total agricultural land)", 
"Urban land area where elevation is below 5 meters (% of total land area)", 
"Permanent cropland (% of land area)", 
"Arable land (hectares)", 
"Fertilizer consumption (% of fertilizer production)",
"Marine protected areas (% of territorial waters)", 
"Annual freshwater withdrawals, total (% of internal resources)", 
"Annual freshwater withdrawals, domestic (% of total freshwater withdrawal)", 
"Capture fisheries production (metric tons)",
"Terrestrial protected areas (% of total land area)", 
"Annual freshwater withdrawals, total (billion cubic meters)", 
"Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)", 
"Aquaculture production (metric tons)", 
"Population in largest city", 
"Rural population living in areas where elevation is below 5 meters (% of total population)",
"Agriculture, forestry, and fishing, value added (constant LCU)", 
"Agriculture, forestry, and fishing, value added (current US$)",
"Cereal production (metric tons)", 
"Average precipitation in depth (mm per year)", 
"Land area where elevation is below 5 meters (% of total land area)", 
"Rural land area where elevation is below 5 meters (sq. km)", 
"Arable land (hectares per person)", 
"Fertilizer consumption (kilograms per hectare of arable land)",
"Agriculture, forestry, and fishing, value added (% of GDP)", 
"Agriculture, forestry, and fishing, value added (current LCU)",
"Agriculture, forestry, and fishing, value added (annual % growth)", 
"Agriculture, forestry, and fishing, value added per worker (constant 2015 US$)"
]

exp_choices = [
"High-technology exports (% of manufactured exports)", 
"Export value index (2015 = 100)", 
"Merchandise exports to low- and middle-income economies in Sub-Saharan Africa (% of total merchandise exports)", 
"Merchandise exports to low- and middle-income economies in Europe & Central Asia (% of total merchandise exports)", 
"Merchandise exports (current US$)", 
"Insurance and financial services (% of commercial service exports)",
"Agricultural raw materials exports (% of merchandise exports)",
"Net barter terms of trade index (2015 = 100)",
"Merchandise imports by the reporting economy, residual (% of total merchandise imports)", 
"Merchandise imports from low- and middle-income economies in Latin America & the Caribbean (% of total merchandise imports)", 
"Merchandise imports from high-income economies (% of total merchandise imports)", 
"Manufactures imports (% of merchandise imports)", 
"Food imports (% of merchandise imports)", 
"Tariff rate, applied, weighted mean, primary products (%)", 
"Share of tariff lines with international peaks, primary products (%)", 
"Tariff rate, applied, weighted mean, all products (%)", 
"Share of tariff lines with international peaks, all products (%)", 
"Tariff rate, applied, weighted mean, manufactured products (%)",
"Share of tariff lines with international peaks, manufactured products (%)", 
"Merchandise trade (% of GDP)",
"Exports of goods and services (constant 2015 US$)",
"Arms exports (SIPRI trend indicator values)",
"Lead time to export, median case (days)",
"Imports of goods and services (% of GDP)",
"Imports of goods and services (current LCU)",
"Exports of goods and services (constant LCU)",
"Exports of goods and services (current US$)",
"Exports of goods, services and primary income (BoP, current US$)",
"Service imports (BoP, current US$)",
"Fuel exports (% of merchandise exports)",
"Export volume index (2015 = 100)",
"Transport services (% of commercial service imports)", 
"Merchandise imports from low- and middle-income economies within region (% of total merchandise imports)", 
"Merchandise imports from low- and middle-income economies in South Asia (% of total merchandise imports)", 
"Merchandise imports from low- and middle-income economies in East Asia & Pacific (% of total merchandise imports)", 
"Merchandise imports from economies in the Arab World (% of total merchandise imports)", 
"ICT goods imports (% total goods imports)",
"Import unit value index (2015 = 100)",
"Tariff rate, most favored nation, simple mean, primary products (%)",
"Binding coverage, primary products (%)",
"Tariff rate, most favored nation, simple mean, all products (%)", 
"Binding coverage, all products (%)", 
"Tariff rate, most favored nation, simple mean, manufactured products (%)", 
"Binding coverage, manufactured products (%)",
"Imports of goods and services (constant LCU)",
"Imports of goods and services (current US$)",
"Exports of goods and services (annual % growth)",
"Arms imports (SIPRI trend indicator values)",
"Time to import, border compliance (hours)",
"Computer, communications and other services (% of commercial service exports)", 
"Merchandise exports by the reporting economy, residual (% of total merchandise exports)", 
"Merchandise exports to low- and middle-income economies in Latin America & the Caribbean (% of total merchandise exports)", 
"Merchandise exports to high-income economies (% of total merchandise exports)", 
"Manufactures exports (% of merchandise exports)", 
"Food exports (% of merchandise exports)", 
"Medium and high-tech exports (% manufactured exports)", 
"Commercial service imports (current US$)",
"Merchandise imports by the reporting economy (current US$)", 
"Merchandise imports from low- and middle-income economies in Middle East & North Africa (% of total merchandise imports)", 
"Merchandise imports from low- and middle-income economies outside region (% of total merchandise imports)", 
"Ores and metals imports (% of merchandise imports)", 
"Fuel imports (% of merchandise imports)", 
"Tariff rate, most favored nation, weighted mean, primary products (%)", 
"Tariff rate, applied, simple mean, primary products (%)", 
"Tariff rate, most favored nation, weighted mean, all products (%)", 
"Tariff rate, applied, simple mean, all products (%)", 
"Tariff rate, most favored nation, weighted mean, manufactured products (%)", 
"Tariff rate, applied, simple mean, manufactured products (%)", 
"Import volume index (2015 = 100)",
"Time to export, border compliance (hours)",
"Taxes on exports (% of tax revenue)",
"Time to import, documentary compliance (hours)",
"High-technology exports (current US$)", 
"Merchandise exports to low- and middle-income economies within region (% of total merchandise exports)", 
"Merchandise exports to low- and middle-income economies in South Asia (% of total merchandise exports)", 
"Merchandise exports to low- and middle-income economies in East Asia & Pacific (% of total merchandise exports)", 
"Merchandise exports to economies in the Arab World (% of total merchandise exports)", 
"ICT goods exports (% of total goods exports)", 
"Export unit value index (2015 = 100)", 
"Travel services (% of commercial service imports)", 
"Import value index (2015 = 100)", 
"Merchandise imports from low- and middle-income economies in Sub-Saharan Africa (% of total merchandise imports)", 
"Merchandise imports from low- and middle-income economies in Europe & Central Asia (% of total merchandise imports)", 
"Merchandise imports (current US$)",
"Insurance and financial services (% of commercial service imports)",
"Agricultural raw materials imports (% of merchandise imports)",
"Share of tariff lines with specific rates, primary products (%)", 
"Bound rate, simple mean, primary products (%)", 
"Share of tariff lines with specific rates, all products (%)", 
"Bound rate, simple mean, all products (%)", 
"Share of tariff lines with specific rates, manufactured products (%)", 
"Bound rate, simple mean, manufactured products (%)",
"International tourism, expenditures (% of total imports)",
"International tourism, expenditures for passenger transport items (current US$)",
"International tourism, number of departures",
"Travel services (% of service exports, BoP) Service exports (BoP, current US$)",
"Net trade in goods (BoP, current US$)",
"Imports of goods, services and primary income (BoP, current US$) Insurance and financial services (% of service imports, BoP)",
"Trade in services (% of GDP)",
"Exports as a capacity to import (constant LCU)"
]

war_options = [
"Internally displaced persons, total displaced by conflict and violence (number of people)",
"Death rate, crude (per 1,000 people)",
"Completeness of death registration with cause-of-death information (%)",
"Number of maternal deaths",
"Number of neonatal deaths", 
"Number of infant deaths", 
"Number of deaths ages 10-14 years",
"Battle-related deaths (number of people)",
"Lifetime risk of maternal death (1 in: rate varies by country)",
"Cause of death, by injury (% of total) Number of deaths ages 15-19 years",
"Lifetime risk of maternal death (%)",
"Number of under-five deaths", 
"Number of deaths ages 20-24 years",
"Cause of death, by non-communicable diseases (% of total)", 
"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)", 
"Number of deaths ages 5-9 years",
]

econ_options = [

"Claims on other sectors of the domestic economy (annual growth as % of broad money)",
"Gross domestic savings (% of GDP)", 
"Oil rents (% of GDP)",
"GDP per capita growth (annual %)",
"Natural gas rents (% of GDP)",
"GDP growth (annual %)",
"GDP (current US$)",
"Discrepancy in expenditure estimate of GDP (current LCU) Inflation, GDP deflator (annual %)",
"Industry (including construction), value added (% of GDP)",
"Gross capital formation (% of GDP)",
"Agriculture, forestry, and fishing, value added (% of GDP)",
"External balance on goods and services (% of GDP)",
"General government final consumption expenditure (% of GDP)",
"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2021 PPP)",
"GDP per unit of energy use (constant 2021 PPP $ per kg of oil equivalent)",
"Energy intensity level of primary energy (MJ/$2017 PPP GDP)",
"Foreign direct investment, net inflows (% of GDP)",
"Gross fixed capital formation, private sector (% of GDP)",
"Gross national expenditure (% of GDP)",
"Households and NPISHs final consumption expenditure (% of GDP)",
"Government expenditure per student, secondary (% of GDP per capita)",
"Revenue, excluding grants (% of GDP)",
"Net investment in nonfinancial assets (% of GDP)",
"Central government debt, total (% of GDP)",
"Research and development expenditure (% of GDP)",
"Claims on other sectors of the domestic economy (% of GDP)",
"Broad money (% of GDP)",
"Stocks traded, total value (% of GDP)",
"Personal remittances, received (% of GDP)",
"Government expenditure on education, total (% of GDP)",
"Tax revenue (% of GDP)",
"Domestic credit provided by financial sector (% of GDP)",
"Monetary Sector credit to private sector (% GDP)",
"Water productivity, total (constant 2015 US$ GDP per cubic meter of total freshwater withdrawal)",
"Net lending (+) / net borrowing (-) (% of GDP)",
"Net incurrence of liabilities, total (% of GDP)",
"Net acquisition of financial assets (% of GDP)",
"Carbon intensity of GDP (kg CO2e per constant 2015 US$ of GDP)",
"GDP per person employed (constant 2021 PPP $)",
"Current health expenditure (% of GDP)",
"Government expenditure per student, tertiary (% of GDP per capita)",
"Government expenditure per student, primary (% of GDP per capita)",
"Gross savings (% of GDP)",
"Total natural resources rents (% of GDP)",
"GDP per capita (constant LCU)",
"GDP per capita (current US$)",
"GDP (constant LCU)",
"GDP (current LCU)",
"Discrepancy in expenditure estimate of GDP (constant LCU)",
"Inflation, GDP deflator: linked series (annual %)",
"Services, value added (% of GDP)",
"Expense (% of GDP)",
"Claims on central government, etc. (% GDP)",
"Domestic credit to private sector by banks (% of GDP)",
"Carbon intensity of GDP (kg CO2e per 2021 PPP $ of GDP)",
"GDP per capita, PPP (constant 2021 international $)",
"GDP per capita (constant 2015 US$)",
"GDP, PPP (constant 2021 international $)",
"GDP (constant 2015 US$)",
"Mineral rents (% of GDP)",
"GDP deflator: linked series (base year varies by country)",
"Coal rents (% of GDP)",
"GDP per unit of energy use (PPP $ per kg of oil equivalent)",
"Market capitalization of listed domestic companies (% of GDP)",
"Current account balance (% of GDP) Foreign direct investment, net outflows (% of GDP)",
"Trade in services (% of GDP)",
"Domestic general government health expenditure (% of GDP)",
"PPP conversion factor, GDP (LCU per international $)",
"GDP per capita, PPP (current international $)",
"GDP per capita (current LCU)",
"GDP, PPP (current international $)",
"GDP: linked series (current LCU)",
"Forest rents (% of GDP)",
"GDP deflator (base year varies by country)",
"Manufacturing, value added (% of GDP)",
"Trade (% of GDP)",
"Gross fixed capital formation (% of GDP)",
"Exports of goods and services (% of GDP)",
"Final consumption expenditure (% of GDP)",
"Gross savings (% of GNI)",
"GNI per capita, PPP (current international $)",
"GNI per capita (current LCU)",
"GNI (constant LCU)", 
"GNI (current LCU)",
"Adjusted savings: natural resources depletion (% of GNI)",
"Cost of business start-up procedures (% of GNI per capita)",
"Cost of business start-up procedures, male (% of GNI per capita)",
"Net ODA provided to the least developed countries (% of GNI)",
"Cost of business start-up procedures, female (% of GNI per capita)",
"External debt stocks (% of GNI)",
"Net ODA provided, total (% of GNI)",
"GNI per capita, PPP (constant 2021 international $)",
"GNI per capita (constant 2015 US$)",
"GNI, PPP (current international $)",
"GNI: linked series (current LCU)",
"Adjusted net savings, excluding particulate emission damage (% of GNI)",
"Adjusted savings: gross savings (% of GNI)",
"Adjusted savings: energy depletion (% of GNI)",
"Adjusted savings: consumption of fixed capital (% of GNI)",
"Adjusted savings: carbon dioxide damage (% of GNI)",
"Present value of external debt (% of GNI)",
"GNI per capita (constant LCU)",
"GNI per capita, Atlas method (current US$)",
"GNI growth (annual %)",
"GNI (current US$)",
"Adjusted net savings, including particulate emission damage (% of GNI)",
"Adjusted savings: net national savings (% of GNI)",
"Adjusted savings: particulate emission damage (% of GNI)",
"Adjusted savings: mineral depletion (% of GNI)",
"Adjusted savings: net forest depletion (% of GNI)",
"Adjusted savings: education expenditure (% of GNI)",
"Net ODA received (% of GNI)",
"GNI per capita growth (annual %)",
"GNI, PPP (constant 2021 international $)",
"GNI (constant 2015 US$)",
"GNI, Atlas method (current US$)",
"Public and publicly guaranteed debt service (% of GNI)",
"Total debt service (% of GNI)"
]

health_options = [
"Completeness of birth registration, urban (%)",
"Wanted fertility rate (births per woman)", 
"Life expectancy at birth, male (years)", 
"Mortality rate, infant (per 1,000 live births)",
"Adolescent fertility rate (births per 1,000 women ages 15-19)",
"Completeness of birth registration, male (%)",
"Life expectancy at birth, female (years)",
"Low-birthweight babies (% of births)",
"Mortality rate, under-5, female (per 1,000 live births)",
"Completeness of birth registration (%)",
"Completeness of birth registration, female (%)",
"Sex ratio at birth (male births per female births)",
"Fertility rate, total (births per woman)",
"Mortality rate, infant, male (per 1,000 live births)",
"Maternal mortality ratio (modeled estimate, per 100,000 live births)",
"Mortality rate, neonatal (per 1,000 live births)",
"Mortality rate, under-5, male (per 1,000 live births)",
"Maternal mortality ratio (national estimate, per 100,000 live births)",
"Completeness of birth registration, rural (%)",
"Mortality rate, under-5 (per 1,000 live births)",
"Proportion of population spending more than 25% of household consumption or income on out-of-pocket health care expenditure (%)",
"Proportion of population pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Proportion of population pushed or further pushed below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Proportion of population pushed further below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Women participating in the three decisions (own health care, major household purchases, and visiting family) (% of women age 15-49)",
"Women making their own informed decisions regarding sexual relations, contraceptive use and reproductive health care (% of women age 15-49)",
"Proportion of population pushed or further pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Proportion of population spending more than 10% of household consumption or income on out-of-pocket health care expenditure (%)", 
"Proportion of population pushed further below the 60% median consumption poverty line by out-of-pocket health care expenditure (%)",
"Proportion of population pushed below the $3.65 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)", 
"Proportion of population pushed further below the $2.15 ($ 2017 PPP) poverty line by out-of-pocket health care expenditure (%)",
"Cause of death, by non-communicable diseases (% of total)", 
"Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)",
"Condom use, population ages 15-24, female (% of females ages 15-24)",
"Condom use, population ages 15-24, male (% of males ages 15-24)",
"Proportion of women subjected to physical and/or sexual violence in the last 12 months (% of ever-partnered women ages 15-49)",
"Prevalence of anemia among women of reproductive age (% of women ages 15-49)",
"Women who believe a husband is justified in beating his wife when she refuses sex with him (%)"
]

politics_choices = [
"Voice and Accountability: Standard Error",
"Voice and Accountability: Number of Sources",
"Net official development assistance received (current US$)",
"Net official development assistance and official aid received (current US$)",
"Net official flows from UN agencies, UNWTO (current US$)",
"Net official flows from UN agencies, UNPBF (current US$)",
"Net official flows from UN agencies, UNEP (current US$)",
"Net official flows from UN agencies, UNCTAD (current US$)",
"Net official flows from UN agencies, UNAIDS (current US$)",
"Control of Corruption: Percentile Rank",
"Net official flows from UN agencies, FAO (current US$)",
"Net financial flows, IMF concessional (NFL, current US$)",
"Net official flows from UN agencies, UNICEF (current US$)",
"Net official flows from UN agencies, SDGFUND (current US$)",
"Net official flows from UN agencies, IAEA (current US$)",
"Net official flows from UN agencies, SPRP (current US$)",
"Net official flows from UN agencies, IFAD (current US$)",
"Net official flows from UN agencies, CERF (current US$)",
"Net official flows from UN agencies, ILO (current US$)",
"Net official flows from UN agencies, WTO-ITC (current US$)",
"Net official flows from UN agencies, UNWOMEN (current US$)",
"Net official flows from UN agencies, UNIDO (current US$)",
"Net official flows from UN agencies, UNECE (current US$)",
"Net official flows from UN agencies, UNHCR (current US$)",
"Net official development assistance received (constant 2021 US$)",
"Net official aid received (constant 2021 US$)",
"Net official flows from UN agencies, WHO (current US$)",
"Net official flows from UN agencies, UNTA (current US$)",
"Net official flows from UN agencies, UNIDIR (current US$)",
"Net official flows from UN agencies, UNDP (current US$)",
"Net ODA received (% of central government expense)",
"Net ODA received (% of GNI)",
"Net official flows from UN agencies, WFP (current US$)",
"Net official flows from UN agencies, UNRWA (current US$)",
"Net official flows from UN agencies, UNFPA (current US$)",
"Net official flows from UN agencies, UNCOVID (current US$)",
"Net official flows from UN agencies, UNCDF (current US$)",
"Net ODA received per capita (current US$)",
"Net ODA received (% of gross capital formation)",
"Political Stability and Absence of Violence/Terrorism: Percentile Rank, Upper Bound of 90% Confidence Interval",
"Political Stability and Absence of Violence/Terrorism: Estimate",
"Political Stability and Absence of Violence/Terrorism: Percentile Rank, Lower Bound of 90% Confidence Interval",
"Rule of Law: Standard Error",
"Rule of Law: Number of Sources",
"Rule of Law: Percentile Rank",
"Rule of Law: Percentile Rank, Upper Bound of 90% Confidence Interval",
"Rule of Law: Estimate",
"Rule of Law: Percentile Rank, Lower Bound of 90% Confidence Interval",
"Personal remittances, paid (current US$)",
"Net bilateral aid flows from DAC donors, Sweden (current US$)",
"Net bilateral aid flows from DAC donors, Poland (current US$)",
"Net bilateral aid flows from DAC donors, Luxembourg (current US$)",
"Net bilateral aid flows from DAC donors, Italy (current US$)",
"Net bilateral aid flows from DAC donors, Greece (current US$)",
"Net bilateral aid flows from DAC donors, Estonia (current US$)",
"Net bilateral aid flows from DAC donors, Czechia (current US$)",
"Net bilateral aid flows from DAC donors, Belgium (current US$)",
"Net bilateral aid flows from DAC donors, Total (current US$)",
"Net bilateral aid flows from DAC donors, Portugal (current US$)",
"Net bilateral aid flows from DAC donors, Netherlands (current US$)",
"Net bilateral aid flows from DAC donors, Japan (current US$)",
"Net bilateral aid flows from DAC donors, Hungary (current US$)",
"Net bilateral aid flows from DAC donors, Finland (current US$)",
"Net bilateral aid flows from DAC donors, United States (current US$)",
"Net bilateral aid flows from DAC donors, Slovak Republic (current US$)",
"Net bilateral aid flows from DAC donors, Norway (current US$)",
"Net bilateral aid flows from DAC donors, Korea, Rep. (current US$)",
"Net bilateral aid flows from DAC donors, Ireland (current US$)",
"Net bilateral aid flows from DAC donors, France (current US$)",
"Net bilateral aid flows from DAC donors, Slovenia (current US$)",
"Net bilateral aid flows from DAC donors, New Zealand (current US$)",
"Net bilateral aid flows from DAC donors, Lithuania (current US$)",
"Net bilateral aid flows from DAC donors, Iceland (current US$)",
"Net bilateral aid flows from DAC donors, United Kingdom (current US$)",
"Net bilateral aid flows from DAC donors, Spain (current US$)",
"Net bilateral aid flows from DAC donors, Switzerland (current US$)",
"Net bilateral aid flows from DAC donors, Austria (current US$)",
"Net bilateral aid flows from DAC donors, Denmark (current US$)",
"Net bilateral aid flows from DAC donors, European Union institutions (current US$)",
"Net bilateral aid flows from DAC donors, Australia (current US$)",
"Net bilateral aid flows from DAC donors, Germany (current US$)",
"Net bilateral aid flows from DAC donors, Canada (current US$)"
]